In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
train_values = pd.read_csv('train_values.csv')
train_labels = pd.read_csv('train_labels.csv')
test_values = pd.read_csv('test_values.csv')

In [3]:
train_values.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,0z64un,1,normal,128,2,0,0,2,308,0.0,1,45,170,0
1,ryoo3j,2,normal,110,3,0,0,0,214,1.6,0,54,158,0
2,yt1s1x,1,normal,125,4,3,0,2,304,0.0,1,77,162,1
3,l2xjde,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0
4,oyt4ek,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0

In [4]:
X = train_values.drop(columns='patient_id')
X_test = test_values.drop(columns='patient_id')
X.head()
X_test.head()

,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,1,normal,128,2,0,0,2,308,0.0,1,45,170,0
1,2,normal,110,3,0,0,0,214,1.6,0,54,158,0
2,1,normal,125,4,3,0,2,304,0.0,1,77,162,1
3,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0
4,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0

,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,2,reversible_defect,170,1,0,0,2,288,0.2,1,59,159,0
1,1,normal,138,4,0,0,0,183,1.4,0,35,182,0
2,2,reversible_defect,120,4,0,0,2,177,2.5,1,43,120,1
3,1,normal,102,3,1,0,0,318,0.0,0,60,160,0
4,2,normal,138,4,1,0,2,166,3.6,1,61,125,1

In [5]:
train_labels.head()

  patient_id  heart_disease_present
0     0z64un                      0
1     ryoo3j                      0
2     yt1s1x                      1
3     l2xjde                      1
4     oyt4ek                      0

In [6]:
y = train_labels.drop(columns='patient_id')
y=np.array(y).flatten()
y

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0], dtype=int64)

#  Create Cross-Validation split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_CV, y_train, y_CV = train_test_split(X, y, test_size=0.3, random_state=2)

In [9]:
X_train.shape, X_CV.shape

((126, 13), (54, 13))

#  Encode with pandas get_dummies method
---

In [10]:
# Get dummies
X_train = pd.get_dummies(X_train, prefix_sep='_', drop_first=True)
X_test = pd.get_dummies(X_test, prefix_sep='_', drop_first=True)
X_CV = pd.get_dummies(X_CV, prefix_sep='_', drop_first=True)

In [11]:
X_train.head()
X_test.head()

,slope_of_peak_exercise_st_segment,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina,thal_normal,thal_reversible_defect
99,1,150,1,0,1,2,283,1.0,0,58,162,0,1,0
142,1,120,2,0,0,0,263,0.0,1,44,173,0,0,1
161,1,117,4,2,1,0,230,1.4,1,60,160,1,0,1
57,2,120,4,2,0,0,267,1.8,1,62,99,1,0,1
71,1,112,4,0,0,0,204,0.1,1,47,143,0,1,0

,slope_of_peak_exercise_st_segment,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina,thal_normal,thal_reversible_defect
0,2,170,1,0,0,2,288,0.2,1,59,159,0,0,1
1,1,138,4,0,0,0,183,1.4,0,35,182,0,1,0
2,2,120,4,0,0,2,177,2.5,1,43,120,1,0,1
3,1,102,3,1,0,0,318,0.0,0,60,160,0,1,0
4,2,138,4,1,0,2,166,3.6,1,61,125,1,1,0

In [12]:
X_train.dtypes

slope_of_peak_exercise_st_segment         int64
resting_blood_pressure                    int64
chest_pain_type                           int64
num_major_vessels                         int64
fasting_blood_sugar_gt_120_mg_per_dl      int64
resting_ekg_results                       int64
serum_cholesterol_mg_per_dl               int64
oldpeak_eq_st_depression                float64
sex                                       int64
age                                       int64
max_heart_rate_achieved                   int64
exercise_induced_angina                   int64
thal_normal                               uint8
thal_reversible_defect                    uint8
dtype: object

#  Remove Constant Features

In [13]:
# remove constant features
constant_features = [
    feat for feat in X_train.columns if X_train[feat].std() == 0
]

X_train.drop(labels=constant_features, axis=1, inplace=True)
X_CV.drop(labels=constant_features, axis=1, inplace=True)

X_train.shape, X_CV.shape

((126, 14), (54, 14))

# Remove Quasi-constant features

In [14]:
from sklearn.feature_selection import VarianceThreshold

# remove quasi-constant features
sel = VarianceThreshold(
    threshold=0.01)  # 0.1 indicates 99% of observations approximately

sel.fit(X_train)  # fit finds the features with low variance

sum(sel.get_support()) # how many not quasi-constant?

VarianceThreshold(threshold=0.01)

14

In [15]:
features_to_keep = X_train.columns[sel.get_support()]
features_to_keep

Index(['slope_of_peak_exercise_st_segment', 'resting_blood_pressure',
       'chest_pain_type', 'num_major_vessels',
       'fasting_blood_sugar_gt_120_mg_per_dl', 'resting_ekg_results',
       'serum_cholesterol_mg_per_dl', 'oldpeak_eq_st_depression', 'sex', 'age',
       'max_heart_rate_achieved', 'exercise_induced_angina', 'thal_normal',
       'thal_reversible_defect'],
      dtype='object')

In [16]:
# we can then remove the features like this
X_train = sel.transform(X_train)
X_CV = sel.transform(X_CV)

X_train.shape, X_CV.shape

((126, 14), (54, 14))

# Duplicate Features

In [17]:
# sklearn transformations lead to numpy arrays
# here I transform the arrays back to dataframes
# please be mindful of getting the columns assigned
# correctly

X_train= pd.DataFrame(X_train)
X_train.columns = features_to_keep

X_CV= pd.DataFrame(X_CV)
X_CV.columns = features_to_keep

In [18]:
# check for duplicated features in the training set
duplicated_feat = []
for i in range(0, len(X_train.columns)):
    if i % 10 == 0:  # this helps me understand how the loop is going
        print(i)

    col_1 = X_train.columns[i]

    for col_2 in X_train.columns[i + 1:]:
        if X_train[col_1].equals(X_train[col_2]):
            duplicated_feat.append(col_2)
            
len(duplicated_feat)

0
10

0

In [19]:
X_train.drop(labels=duplicated_feat, axis=1, inplace=True)
X_CV.drop(labels=duplicated_feat, axis=1, inplace=True)

X_train.shape, X_CV.shape

((126, 14), (54, 14))

#  Feature Importance

In [20]:
# Feature Importance with Extra Trees Classifier
from sklearn.ensemble import ExtraTreesClassifier
# load data
# feature extraction
model = ExtraTreesClassifier()
model.fit(X_train, y_train)
print(model.feature_importances_)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

[0.06445278 0.04999242 0.08652441 0.1132219  0.02149234 0.03150569
 0.04330815 0.09437597 0.03512997 0.05078969 0.05597461 0.12219714
 0.08655101 0.14448392]

In [21]:
X_train.columns

Index(['slope_of_peak_exercise_st_segment', 'resting_blood_pressure',
       'chest_pain_type', 'num_major_vessels',
       'fasting_blood_sugar_gt_120_mg_per_dl', 'resting_ekg_results',
       'serum_cholesterol_mg_per_dl', 'oldpeak_eq_st_depression', 'sex', 'age',
       'max_heart_rate_achieved', 'exercise_induced_angina', 'thal_normal',
       'thal_reversible_defect'],
      dtype='object')

In [22]:
importance_df = pd.DataFrame()
importance_df['Feature']=X_train.columns
importance_df['Importance']=model.feature_importances_
importance_df.sort_values(by='Importance',ascending=False)

                                 Feature  Importance
13                thal_reversible_defect    0.144484
11               exercise_induced_angina    0.122197
3                      num_major_vessels    0.113222
7               oldpeak_eq_st_depression    0.094376
12                           thal_normal    0.086551
2                        chest_pain_type    0.086524
0      slope_of_peak_exercise_st_segment    0.064453
10               max_heart_rate_achieved    0.055975
9                                    age    0.050790
1                 resting_blood_pressure    0.049992
6            serum_cholesterol_mg_per_dl    0.043308
8                                    sex    0.035130
5                    resting_ekg_results    0.031506
4   fasting_blood_sugar_gt_120_mg_per_dl    0.021492

In [23]:
# #  Remove the lowest importance feature
# X_train.drop(columns='fasting_blood_sugar_gt_120_mg_per_dl',inplace=True)
# X_test.drop(columns='fasting_blood_sugar_gt_120_mg_per_dl',inplace=True)
# X_train.head()

# Fitting using Machine Learning Models
---
*  Logistic Regression
*  Random Forest

In [24]:
test_values.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,olalu7,2,reversible_defect,170,1,0,0,2,288,0.2,1,59,159,0
1,z9n6mx,1,normal,138,4,0,0,0,183,1.4,0,35,182,0
2,5k4413,2,reversible_defect,120,4,0,0,2,177,2.5,1,43,120,1
3,mrg7q5,1,normal,102,3,1,0,0,318,0.0,0,60,160,0
4,uki4do,2,normal,138,4,1,0,2,166,3.6,1,61,125,1

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

#  Fit with Logistic Regression
#clf = LogisticRegression(random_state=4,penalty='l2',solver='liblinear').fit(X_train, y_train)
clf = RandomForestClassifier(n_estimators=1000, max_depth=5,random_state=0).fit(X_train, y_train)

clf.predict(X_test)


#  probability of heart disease
probs = clf.predict_proba(X_test)
probs[:5]

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0], dtype=int64)

array([[0.8074612 , 0.1925388 ],
       [0.85057164, 0.14942836],
       [0.09162484, 0.90837516],
       [0.72903171, 0.27096829],
       [0.28019582, 0.71980418]])

In [26]:
# probability of heart disease (y=1)
probs[:,1]

array([0.1925388 , 0.14942836, 0.90837516, 0.27096829, 0.71980418,
       0.01683334, 0.3535335 , 0.6368839 , 0.11909231, 0.08554775,
       0.16678375, 0.54049039, 0.22640557, 0.79204023, 0.09173836,
       0.01698659, 0.16793794, 0.27472741, 0.80099208, 0.04050359,
       0.95952253, 0.10963258, 0.09584953, 0.0282649 , 0.49412466,
       0.8603783 , 0.48205985, 0.17186264, 0.52459754, 0.01593562,
       0.91621205, 0.27809993, 0.57728899, 0.20846671, 0.10677125,
       0.04921379, 0.37926408, 0.32608495, 0.35929514, 0.21311885,
       0.91464172, 0.14603173, 0.88872765, 0.06671577, 0.89015089,
       0.03058814, 0.07776469, 0.27755801, 0.05607876, 0.4423123 ,
       0.54148819, 0.01642742, 0.92541633, 0.06531882, 0.30311176,
       0.02398546, 0.73472225, 0.15506966, 0.18830496, 0.6945421 ,
       0.0553167 , 0.85121605, 0.13417884, 0.81107336, 0.10699302,
       0.73264993, 0.61508109, 0.51484358, 0.85632534, 0.66940891,
       0.23630503, 0.95016348, 0.93500139, 0.91290989, 0.85208405,
       0.980515  , 0.81365281, 0.46244563, 0.24314475, 0.58224371,
       0.4353486 , 0.20215928, 0.41877736, 0.67442627, 0.1964712 ,
       0.08466284, 0.70837119, 0.14229283, 0.35202886, 0.15563839])

In [27]:
output = pd.DataFrame()

In [28]:
output['patient_id']=test_values['patient_id']
output['heart_disease_present']=probs[:,1]
output

   patient_id  heart_disease_present
0      olalu7               0.192539
1      z9n6mx               0.149428
2      5k4413               0.908375
3      mrg7q5               0.270968
4      uki4do               0.719804
5      kev1sk               0.016833
6      9n6let               0.353534
7      jxmtyg               0.636884
8      51s2ff               0.119092
9      wi9mcs               0.085548
10     741h4l               0.166784
11     1ef64a               0.540490
12     wa2ix6               0.226406
13     8167zl               0.792040
14     n6nldr               0.091738
15     ph85fp               0.016987
16     jfan5p               0.167938
17     7c4iz1               0.274727
18     ukigml               0.800992
19     flwvnq               0.040504
20     5i4fw2               0.959523
21     du1pqf               0.109633
22     vs68qz               0.095850
23     pfyez0               0.028265
24     azvkw2               0.494125
25     cird1i               0.860378
26     3bg32t               0.482060
27     xzd050               0.171863
28     eyi8et               0.524598
29     ce4x2h               0.015936
..        ...                    ...
60     tgpy9u               0.055317
61     pf5wp6               0.851216
62     cj8vj2               0.134179
63     9w6d9j               0.811073
64     3l89wd               0.106993
65     83a6x1               0.732650
66     oua0gr               0.615081
67     j0hl96               0.514844
68     dlkzyg               0.856325
69     r0w4a8               0.669409
70     46dlca               0.236305
71     9fkefu               0.950163
72     6uk6kl               0.935001
73     c7olxr               0.912910
74     iiyx0q               0.852084
75     25vetx               0.980515
76     073vc5               0.813653
77     18abn0               0.462446
78     v5fsfs               0.243145
79     2ekoo7               0.582244
80     5bbknr               0.435349
81     hr6pjx               0.202159
82     r4hsar               0.418777
83     4cezdf               0.674426
84     palhcc               0.196471
85     bwoyg6               0.084663
86     j8i7ve               0.708371
87     t2zn1n               0.142293
88     oxf8kj               0.352029
89     aeiv0y               0.155638

[90 rows x 2 columns]

In [29]:
output.to_csv('prediction_result.csv',index=False)